package com.ecom.service;


import com.ecom.dto.AddressDTO;
import com.ecom.dto.UserRequest;
import com.ecom.dto.UserResponse;
import com.ecom.model.Address;
import com.ecom.model.User;
import com.ecom.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;


@Service
@RequiredArgsConstructor
public class UserService {
    private final UserRepository userRepository;
  //  private List<User> userList = new ArrayList<>();
    private Long nextId= 1L;

//    public UserService(UserRepository userRepository) {
//        this.userRepository = userRepository;
//    }
    // @RequiredArgsConstructor => Lombok will generate one constructor during compile time...
    // @RequiredArgsConstructor => it only includes...1. "final" fields 2. fields mark with @NonNull

    public List<UserResponse> fetchAllUsers (){
        List<User> userList = userRepository.findAll();
        return userList.stream()
                .map(this::mapToUserResponse)
                .collect(Collectors.toList());
    }

    public void addUser (UserRequest userRequest){
    //    user.setId(nextId++); // Now id is autogenerated
     //   userList.add(user); // we will use userRepository instead of userList
        User user = new User();
        updateUserFromRequest(user, userRequest);
        userRepository.save(user);

    }
    public Optional<UserResponse> fetchUser(Long id) {
//        for (User user: userList){
//            if(user.getId().equals(id)){
//                return user;
//            }
//        }
        // this for loop is not efficient to use. so we are thinking otherwise.
//        return userList.stream()
//                .filter(user -> user.getId().equals(id))
//                .findFirst(); // we are not using list now.. so we can remove this
        return userRepository.findById(id)
                .map(this::mapToUserResponse);

    }
//    public boolean updateUser(Long id, User updatedUser){
//        return userList.stream()
//                .filter(user -> user.getId().equals(id))
//                .findFirst()
//                .map(existingUser ->{
//                    existingUser.setFirstName(updatedUser.getFirstName());
//                    existingUser.setLastName(updatedUser.getLastName());
//                    return true;
//                        }
//                        ).orElse(false);
//    } // we don't need this anymore.. we need JPA based operations

public boolean updateUser(Long id, UserRequest updatedUserRequest){
     return userRepository.findById(id)
             .map(existingUser -> {
                updateUserFromRequest(existingUser, updatedUserRequest);
                 userRepository.save(existingUser);
                 return true;
             }).orElse(false);
}


    private void updateUserFromRequest(User user, UserRequest userRequest) {
        user.setFirstName(userRequest.getFirstName());
        user.setLastName(userRequest.getLastName());
        user.setEmail(userRequest.getEmail());
        user.setPhone(userRequest.getPhone());
        if(userRequest.getAddress()!= null){
            Address address = new Address();
            address.setStreet(userRequest.getAddress().getStreet());
            address.setState(userRequest.getAddress().getState());
            address.setCity(userRequest.getAddress().getCity());
            address.setCountry(userRequest.getAddress().getCountry());
            address.setZipcode(userRequest.getAddress().getZipcode());


            user.setAddress(address);
        }

    }

    private UserResponse mapToUserResponse(User user) {

        UserResponse response = new UserResponse();

        response.setId(user.getId()); // use same type (Long) if possible
        response.setFirstName(user.getFirstName());
        response.setLastName(user.getLastName());
        response.setEmail(user.getEmail());
        response.setPhone(user.getPhone());
        response.setRole(user.getRole());

        if (user.getAddress() != null) {

            AddressDTO addressDTO = new AddressDTO();

            addressDTO.setStreet(user.getAddress().getStreet());
            addressDTO.setCity(user.getAddress().getCity());
            addressDTO.setState(user.getAddress().getState());
            addressDTO.setCountry(user.getAddress().getCountry());
            addressDTO.setZipcode(user.getAddress().getZipcode());

            response.setAddress(addressDTO);
        }

        return response;
    }
}
