package com.ecom.service;


import com.ecom.model.User;
import com.ecom.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;


@Service
@RequiredArgsConstructor
public class UserService {
    private final UserRepository userRepository;
  //  private List<User> userList = new ArrayList<>();
    private Long nextId= 1L;

//    public UserService(UserRepository userRepository) {
//        this.userRepository = userRepository;
//    }
    // @RequiredArgsConstructor => Lombok will generate one constructor during compile time...
    // @RequiredArgsConstructor => it only includes...1. "final" fields 2. fields mark with @NonNull

    public List<User> fetchAllUsers (){
        return userRepository.findAll();
    }

    public void addUser (User user){
    //    user.setId(nextId++); // Now id is autogenerated
     //   userList.add(user); // we will use userRepository instead of userList
    userRepository.save(user);

    }

    public Optional<User> fetchUser(Long id) {
//        for (User user: userList){
//            if(user.getId().equals(id)){
//                return user;
//            }
//        }
        // this for loop is not efficient to use. so we are thinking otherwise.
//        return userList.stream()
//                .filter(user -> user.getId().equals(id))
//                .findFirst(); // we are not using list now.. so we can remove this
        return userRepository.findById(id);

    }
//    public boolean updateUser(Long id, User updatedUser){
//        return userList.stream()
//                .filter(user -> user.getId().equals(id))
//                .findFirst()
//                .map(existingUser ->{
//                    existingUser.setFirstName(updatedUser.getFirstName());
//                    existingUser.setLastName(updatedUser.getLastName());
//                    return true;
//                        }
//                        ).orElse(false);
//    } // we don't need this anymore.. we need JPA based operations

public boolean updateUser(Long id, User updatedUser){
     return userRepository.findById(id)
             .map(existingUser -> {
                 existingUser.setFirstName(updatedUser.getFirstName());
                 existingUser.setLastName(updatedUser.getLastName());
                 userRepository.save(existingUser);
                 return true;
             }).orElse(false);
}

}
